### ISSUE TITLE
Requested Feature - Extended Portraits

### ISSUE THREAD

**Issue by TheRealVicere** [ValeTheVioletMote/fecc#2]
Is there any way you could make miniature portraits and blinking/speaking frames to include alongside the main 96x96 portrait? The program I'm using requires these.

**Comment by ValeTheVioletMote** [comment]
I don't think that's within my ability to do. That said, you may want to check out [Klokgen's AI work](https://civitai.com/models/13246/klokgen-fire-emblem-style-character-generator). I believe he's getting close to the point where AI can produce the frames accurately. More details in his discord.

**Comment by TheRealVicere** [comment]
I see. Thanks for the info and the redirect. Love the tool by the way!
